# Generated by Django 4.1.9 on 2023-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_foo_rename_foobar_bar_rename_foo_bar_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='fruit_salad',
            field=models.IntegerField(default=0),
        ),
    ]
